# https://taskfile.dev

version: "3"

tasks:
  default:
    silent: true
    cmds:
      - task --list-all

  build:
    cmds:
      - go build -o bin/UpdateWallpaper.exe ./cmd/UpdateWallpaper

  run:
    cmds:
      - task: build
      - ./bin/UpdateWallpaper.exe
